export async function POST(request: Request) {
  try {
    const body = await request.json()
    const { pathways, userResponses } = body

    // Mock opportunities database - in production, this would query your real database
    // or use AI to generate personalized opportunities
    const opportunitiesDatabase: Record<string, Array<any>> = {
      "Software Engineering": [
        {
          id: "1",
          type: "internship",
          title: "Summer Internship - Backend Development",
          description: "Join a growing tech startup in Mexico City working on scalable backend systems",
          provider: "TechStartup LATAM",
          company: "TechStartup LATAM",
          duration: "3 months",
          location: "Remote/Mexico City",
        },
        {
          id: "2",
          type: "course",
          title: "Advanced Node.js & TypeScript",
          description: "Master modern backend development with Node.js, TypeScript, and PostgreSQL",
          provider: "Coursera",
          duration: "8 weeks",
          level: "Intermediate",
        },
        {
          id: "3",
          type: "study_plan",
          title: "Full Stack Developer Roadmap",
          description: "6-month comprehensive program covering frontend, backend, databases, and DevOps",
          provider: "Self-paced",
          duration: "6 months",
        },
      ],
      "Product Management": [
        {
          id: "4",
          type: "internship",
          title: "Product Management Internship",
          description: "Work with experienced PMs at a Series B startup building products for LATAM",
          provider: "InnovateCo",
          company: "InnovateCo",
          duration: "6 months",
          location: "Hybrid - Buenos Aires",
        },
        {
          id: "5",
          type: "course",
          title: "Product Management Fundamentals",
          description: "Learn product strategy, user research, and roadmap planning",
          provider: "Reforge",
          duration: "4 weeks",
          level: "Beginner",
        },
        {
          id: "6",
          type: "summer_camp",
          title: "Product Leader Summit",
          description: "Network with product leaders and learn from industry experts",
          provider: "Product School",
          duration: "1 week",
          location: "Online",
          dates: "July 2025",
        },
      ],
      "UX/UI Design": [
        {
          id: "7",
          type: "internship",
          title: "Design Internship - Design Systems",
          description: "Build design systems and components for a growing fintech platform",
          provider: "FinTechXYZ",
          company: "FinTechXYZ",
          duration: "4 months",
          location: "Remote",
        },
        {
          id: "8",
          type: "course",
          title: "Interaction Design & Prototyping",
          description: "Master Figma, prototyping, and user-centered design principles",
          provider: "DesignLab",
          duration: "10 weeks",
          level: "Beginner",
        },
        {
          id: "9",
          type: "study_plan",
          title: "UX Design Career Path",
          description: "Comprehensive guide to becoming a professional UX designer",
          provider: "Nielsen Norman Group",
          duration: "3 months",
        },
      ],
      "Data Science": [
        {
          id: "10",
          type: "internship",
          title: "Data Science Internship - ML Engineering",
          description: "Work on machine learning projects in production environments",
          provider: "DataCorp LATAM",
          company: "DataCorp LATAM",
          duration: "6 months",
          location: "São Paulo - Remote",
        },
        {
          id: "11",
          type: "course",
          title: "Machine Learning Specialization",
          description: "Deep dive into ML algorithms, deep learning, and MLOps",
          provider: "Coursera",
          duration: "12 weeks",
          level: "Intermediate",
        },
        {
          id: "12",
          type: "study_plan",
          title: "Data Science 100 Days Challenge",
          description: "Intensive daily learning program with real-world projects",
          provider: "DataCamp",
          duration: "100 days",
        },
      ],
      "Startup Founder": [
        {
          id: "13",
          type: "internship",
          title: "Founder Immersion - Startup Accelerator",
          description: "Fast-track program for aspiring entrepreneurs with mentorship",
          provider: "Startup Academy LATAM",
          company: "Startup Academy LATAM",
          duration: "3 months",
          location: "Hybrid - Colombia",
        },
        {
          id: "14",
          type: "course",
          title: "How to Start a Startup",
          description: "Learn fundraising, product-market fit, and scaling strategies",
          provider: "Y Combinator",
          duration: "6 weeks",
          level: "Beginner",
        },
        {
          id: "15",
          type: "summer_camp",
          title: "Founder Bootcamp 2024",
          description: "Intensive summer program with investor pitch preparation",
          provider: "FounderInstitute",
          duration: "8 weeks",
          location: "Mexico City",
          dates: "June-August 2025",
        },
      ],
      "Business Strategy": [
        {
          id: "16",
          type: "course",
          title: "Strategic Planning & Business Execution",
          description: "Learn frameworks used by top consultants at McKinsey and Bain",
          provider: "MasterClass",
          duration: "8 weeks",
          level: "Intermediate",
        },
        {
          id: "17",
          type: "internship",
          title: "Management Consulting Internship",
          description: "Work on strategic projects with multinational companies",
          provider: "ConsultingCorp",
          company: "ConsultingCorp",
          duration: "6 months",
          location: "Hybrid - Santiago",
        },
        {
          id: "18",
          type: "study_plan",
          title: "MBA Preparation Program",
          description: "Prepare for MBA applications and business leadership",
          provider: "Self-curated",
          duration: "4 months",
        },
      ],
      // Spanish pathway names mapping
      "Ingeniería de Software": [
        {
          id: "1",
          type: "internship",
          title: "Pasantía de Verano - Desarrollo Backend",
          description: "Únete a una startup tecnológica en crecimiento en Ciudad de México trabajando en sistemas backend escalables",
          provider: "TechStartup LATAM",
          company: "TechStartup LATAM",
          duration: "3 meses",
          location: "Remoto/Ciudad de México",
        },
        {
          id: "2",
          type: "course",
          title: "Node.js y TypeScript Avanzado",
          description: "Domina el desarrollo backend moderno con Node.js, TypeScript y PostgreSQL",
          provider: "Coursera",
          duration: "8 semanas",
          level: "Intermedio",
        },
        {
          id: "3",
          type: "study_plan",
          title: "Ruta de Desarrollador Full Stack",
          description: "Programa integral de 6 meses que cubre frontend, backend, bases de datos y DevOps",
          provider: "Autodidacta",
          duration: "6 meses",
        },
      ],
      "Gestión de Productos": [
        {
          id: "4",
          type: "internship",
          title: "Pasantía en Gestión de Productos",
          description: "Trabaja con PMs experimentados en una startup Serie B construyendo productos para LATAM",
          provider: "InnovateCo",
          company: "InnovateCo",
          duration: "6 meses",
          location: "Híbrido - Buenos Aires",
        },
        {
          id: "5",
          type: "course",
          title: "Fundamentos de Gestión de Productos",
          description: "Aprende estrategia de producto, investigación de usuarios y planificación de roadmap",
          provider: "Reforge",
          duration: "4 semanas",
          level: "Principiante",
        },
        {
          id: "6",
          type: "summer_camp",
          title: "Cumbre de Líderes de Producto",
          description: "Conéctate con líderes de producto y aprende de expertos de la industria",
          provider: "Product School",
          duration: "1 semana",
          location: "Online",
          dates: "Julio 2025",
        },
      ],
      "Diseño UX/UI": [
        {
          id: "7",
          type: "internship",
          title: "Pasantía de Diseño - Sistemas de Diseño",
          description: "Construye sistemas de diseño y componentes para una plataforma fintech en crecimiento",
          provider: "FinTechXYZ",
          company: "FinTechXYZ",
          duration: "4 meses",
          location: "Remoto",
        },
        {
          id: "8",
          type: "course",
          title: "Diseño de Interacción y Prototipado",
          description: "Domina Figma, prototipado y principios de diseño centrado en el usuario",
          provider: "DesignLab",
          duration: "10 semanas",
          level: "Principiante",
        },
        {
          id: "9",
          type: "study_plan",
          title: "Ruta de Carrera en Diseño UX",
          description: "Guía completa para convertirte en diseñador UX profesional",
          provider: "Nielsen Norman Group",
          duration: "3 meses",
        },
      ],
      "Ciencia de Datos": [
        {
          id: "10",
          type: "internship",
          title: "Pasantía en Ciencia de Datos - Ingeniería ML",
          description: "Trabaja en proyectos de machine learning en entornos de producción",
          provider: "DataCorp LATAM",
          company: "DataCorp LATAM",
          duration: "6 meses",
          location: "São Paulo - Remoto",
        },
        {
          id: "11",
          type: "course",
          title: "Especialización en Machine Learning",
          description: "Profundiza en algoritmos de ML, deep learning y MLOps",
          provider: "Coursera",
          duration: "12 semanas",
          level: "Intermedio",
        },
        {
          id: "12",
          type: "study_plan",
          title: "Desafío de 100 Días de Ciencia de Datos",
          description: "Programa intensivo de aprendizaje diario con proyectos del mundo real",
          provider: "DataCamp",
          duration: "100 días",
        },
      ],
      "Fundador de Startup": [
        {
          id: "13",
          type: "internship",
          title: "Inmersión de Fundador - Aceleradora de Startups",
          description: "Programa acelerado para emprendedores aspirantes con mentoría",
          provider: "Startup Academy LATAM",
          company: "Startup Academy LATAM",
          duration: "3 meses",
          location: "Híbrido - Colombia",
        },
        {
          id: "14",
          type: "course",
          title: "Cómo Iniciar una Startup",
          description: "Aprende recaudación de fondos, product-market fit y estrategias de escalamiento",
          provider: "Y Combinator",
          duration: "6 semanas",
          level: "Principiante",
        },
        {
          id: "15",
          type: "summer_camp",
          title: "Bootcamp de Fundadores 2024",
          description: "Programa intensivo de verano con preparación de pitch para inversores",
          provider: "FounderInstitute",
          duration: "8 semanas",
          location: "Ciudad de México",
          dates: "Junio-Agosto 2025",
        },
      ],
      "Estrategia de Negocios": [
        {
          id: "16",
          type: "course",
          title: "Planificación Estratégica y Ejecución de Negocios",
          description: "Aprende frameworks usados por consultores top de McKinsey y Bain",
          provider: "MasterClass",
          duration: "8 semanas",
          level: "Intermedio",
        },
        {
          id: "17",
          type: "internship",
          title: "Pasantía en Consultoría de Gestión",
          description: "Trabaja en proyectos estratégicos con empresas multinacionales",
          provider: "ConsultingCorp",
          company: "ConsultingCorp",
          duration: "6 meses",
          location: "Híbrido - Santiago",
        },
        {
          id: "18",
          type: "study_plan",
          title: "Programa de Preparación para MBA",
          description: "Prepárate para aplicaciones a MBA y liderazgo empresarial",
          provider: "Auto-curado",
          duration: "4 meses",
        },
      ],
    }

    // Collect opportunities for selected pathways
    const opportunities: any[] = []
    pathways.forEach((pathway: string) => {
      const pathwayOps = opportunitiesDatabase[pathway as keyof typeof opportunitiesDatabase] || []
      opportunities.push(...pathwayOps)
    })

    return Response.json({
      success: true,
      opportunities,
    })
  } catch (error) {
    console.error("[v0] Error fetching opportunities:", error)
    return Response.json(
      {
        success: false,
        error: error instanceof Error ? error.message : "Failed to fetch opportunities",
      },
      { status: 500 },
    )
  }
}
